spring.application.name=SchemaSync
# ==========================
# PostgreSQL (Supabase)
# ==========================
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.clklcvnytonkrxputvmm

spring.datasource.password=#Viraj-4286%
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
#
#JWT_SECRET=g73DuQ0NP6BWK9ylVlWqFp3weSmZARvRe5mhrIe6EprWGliJzHqCImmX48jP7Q+6ZlYXE3R1eBKVyc1xT6MT7Q==
#JWT_EXPIRATION_MS=86400000