# ==========================================
# Application General Settings
# ==========================================
spring.application.name=SchemaSync

# ==========================================
# Database (Supabase PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.clklcvnytonkrxputvmm
spring.datasource.password=#Viraj-4286%
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# Security & JWT Configuration
# ==========================================
jwt.secret=g73DuQ0NP6BWK9ylVlWqFp3weSmZARvRe5mhrIe6EprWGliJzHqCImmX48jP7Q+6ZlYXE3R1eBKVyc1xT6MT7Q==
jwt.expiration=86400000

# ==========================================
# Apache Kafka Core Configuration (Aiven)
# ==========================================
spring.kafka.bootstrap-servers=kafka-cluster-virajpadawal4286-6b22.e.aivencloud.com:11045

# Kafka Security & SSL Properties
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="avnadmin" password="AVNS_Q3_5ipgKQiQgZu-bZ6u";

# SSL Truststore (Aiven PEM Certificate)
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.certificates=-----BEGIN CERTIFICATE-----\nMIIERDCCAqygAwIBAgIUW0cxwqU7Nggc4J2yy/SJhip73x8wDQYJKoZIhvcNAQEM\nBQAwOjE4MDYGA1UEAwwvMzk5MmVjOTAtZjQyZi00ZWQ3LTkwMjgtMTkzN2I0MTVh\nOWM4IFByb2plY3QgQ0EwHhcNMjYwNzEyMTMyMjEzWhcNMzYwNzA5MTMyMjEzWjA6\nMTgwNgYDVQQDDC8zOTkyZWM5MC1mNDJmLTRlZDctOTAyOC0xOTM3YjQxNWE5Yzgg\nUHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMXVVVuz\nW8a4SmRSkyG16fPrE/JCEBo+XJbGPeOy2rAKur45HQlvbkPou/9ui0sSPcEPRt3R\nh0yFCwiM6/+witCdL1Tg6/FrKMdTzuj5KNUUMY/9HKlb09DUToF0c38u1Qcos6Rt\nokPq9qIaOPZh3BUG48ZOf2hT6wuiwc8V7lvrlzOnM4cqN+PlRphttcsY1CyLUs+9\nOLwy+QWgPDUD+JlkjQWyoXB1IcsZ7eVUs5+mous1+MfG37FyMjZl48Fh0H6dBh9Z\nCg7YAljJKIDTYVLRfSNUtt0MRNQqjGn+97y5gD5UaWHSM7eFhetuJQi/KC9ji9Kv\nP6BHU3v6eZh9gP8nyqiRRjRw8r4tOvGd8ISq8Gngo6U6oFAui6UKIBKqT7JZE6kH\n1XysZDy83nq8pSndScwiNLnexHN906fIXHOkr7bfLbpCbtr0X2ekNhcGldeVS8xy\nILze2qN97I4xPOvlWt8VeqJo8dRABTeVqm7x9GeUJUDMV0xRmy1rZw+xWwIDAQAB\no0IwQDAdBgNVHQ4EFgQUVGcC89HnHdu4B8DrG4vHBj1DfCYwEgYDVR0TAQH/BAgw\nBgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAH3+lIxEGmVU\nbQ65hTOjnUmHgx26a4iguyF0nEHzHxJSYd1wsH/CWTQFpcDwaQX3a/jN7gjVtsTc\nICdtk2ucBle/NO6wZHV+ckbs3iQmC3s6SBDKuu6V6MPgxKKPl3K052gy/6ODaZtK\n8mEAND9LJuSgs39AYHfk5b+XvlotgNWUkUG5BjYaociaSRmu2e7n4S3RZzoPQYsl\nOvnk0UZygS3CLb0prKLK9LFHQsQKUukKonVOMRThj1IUHDhgpUiR0JMgfI2ijFBZ\nKuOwUOr7SKUUYQ78TMjSdWdqca6FLUIXeLFizpKGrIrn8vzYUxyV8lxPPsCNGdy8\nfWDoGm34K4iZc1dJnu/Tli3xkH3rGCFWZxmw4BJJ9gxB72qgj8YdNC2q0Gif1mk5\nUjIqj0dzcxYYLfTn3nyyvWQIZnZpN/nemR/h6CTbFq++ycEhgjkOUe2W2YoN9Jit\nHAnJs6AX2MIDDjbGsT2vByiT9cZCFjvONMBxJrEF3H5dmSoyDuEbKw==\n-----END CERTIFICATE-----
# ==========================================
# Kafka Consumer Configuration
# ==========================================
#spring.kafka.consumer.group-id=schemasync-consumer-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.enable-auto-commit=false
#spring.kafka.listener.ack-mode=MANUAL
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ==========================================
# Kafka Producer Configuration
# ==========================================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# ==========================================
# Redis Configuration
# ==========================================

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:books-wineberry-sisters-11988.db.redis.io}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:12158}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME:default}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:E7lRsvYPjH694LaCFks0L3w0ZJKMp0mJ}
spring.data.redis.timeout=2000ms
spring.data.redis.connect-timeout=1000ms
gemini.api-key=AQ.Ab8RN6IcGKnB53MP1tel876ys1iVUL8piRNxrDMvaXKB_OPoMw
gemini.model-name=gemini-flash-latest

# ==========================================
# Kafka Consumer Configuration
# ==========================================
spring.kafka.consumer.group-id=schemasync-consumer-group-v5-1
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=MANUAL
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*